additional.info=Additional Info
pirate-crew.captain=Monkey D. Luffy
pirate-crew.first-mate=Roronoa Zoro
pirate-crew.navigator=Nami
pirate-crew.sniper=Usopp
pirate-crew.cook=Vinsmoke Sanji
pirate-crew.doctor=Tony Tony Chopper
pirate-crew.historian=Nico Robin
pirate-crew.number=7